commit
Helena-74/nodejs-homework-rest-api pull request #1
Opened 2023-09-30 17:22 UTC by Helena-74

2023-10-01 05:53 UTC, KhYulian commented on helpers/HttpError.js
> +const HttpError = (status, message = messageList[status]) => {
Використовуйте класи https://javascript.info/custom-errors, використовуйте new при роботі з класами

2023-10-01 05:53 UTC, KhYulian commented on routes/api/contacts.js
>  })
Виносьте схеми валідації окремо e.g. /utils/validation/contactValidationSchemas.js

2023-10-01 05:54 UTC, KhYulian commented on routes/api/contacts.js
> +}
Винесіть функції в окремий файл e.g. controllers/contactControllers.js

2023-10-01 05:54 UTC, KhYulian commented on routes/api/contacts.js
> +    }
Для валідації використовуйте виключно схеми Joi такі перевірки непотрібні

2023-10-01 05:54 UTC, KhYulian requested changes
Потрібні правки. Відписуйте на коменти по мірі виправлення

2023-10-02 20:02 UTC, Helena-74 commented on routes/api/contacts.js
>  })
перенесла в окрему папку e.g. /utils/validation/contactValidationSchemas.js

2023-10-02 20:03 UTC, Helena-74 commented on routes/api/contacts.js
> +}
Винесла функції в окремий файл e.g. controllers/contactControllers.js

2023-10-02 20:03 UTC, Helena-74 commented on routes/api/contacts.js
> +    }
прибрала

2023-10-03 11:54 UTC, merged